// packages/svelte/.storybook/stories/components/tags-input/disabled-editing.svelte
<script lang="ts">
  import { tagsInputStyles } from "@bouquet-ui/design";
  import { XIcon } from "lucide-svelte";
  import { TagsInput } from "../../../../src/lib";

  const styles = tagsInputStyles();
</script>


<TagsInput.Root class={styles.root()} value={["React", "Svelte", "Vue"]} editable={false}>
  <TagsInput.Label class={styles.label()}>Frameworks (Read-only)</TagsInput.Label>
  <TagsInput.Control class={styles.control()}>
    <TagsInput.Context>
      {#snippet render(tags)}
        {#each tags().value as value, index (index)}
          <TagsInput.Item class={styles.item()} {index} {value}>
            <TagsInput.ItemPreview class={styles.itemPreview()}>
              <TagsInput.ItemText class={styles.itemText()}>{value}</TagsInput.ItemText>
              <TagsInput.ItemDeleteTrigger class={styles.itemDeleteTrigger()}>
                <XIcon />
              </TagsInput.ItemDeleteTrigger>
            </TagsInput.ItemPreview>
            <TagsInput.ItemInput class={styles.itemInput()} />
          </TagsInput.Item>
        {/each}
      {/snippet}
    </TagsInput.Context>
    <TagsInput.Input class={styles.input()} placeholder="Add Framework" />
  </TagsInput.Control>
  <TagsInput.ClearTrigger class={styles.clearTrigger()}>Clear all</TagsInput.ClearTrigger>
  <TagsInput.HiddenInput />
</TagsInput.Root>

// packages/vue/.storybook/stories/components/tags-input/disabled-editing.vue
<script setup lang="ts">
  import { tagsInputStyles } from "@bouquet-ui/design";
  import { TagsInput } from "../../../../src";

  const styles = tagsInputStyles();
</script>

<template>
  <TagsInput.Root :class="styles.root()" :allowEditTag="false">
    <TagsInput.Context v-slot="tagsInput">
      <TagsInput.Label :class="styles.label()">Frameworks</TagsInput.Label>
      <TagsInput.Control :class="styles.control()">
        <TagsInput.Item :class="styles.item()" v-for="(value, index) in tagsInput.value" :key="index" :index="index" :value="value">
          <TagsInput.ItemInput :class="styles.itemInput()" />
          <TagsInput.ItemText :class="styles.itemText()">{{ value }}</TagsInput.ItemText>
          <TagsInput.ItemDeleteTrigger :class="styles.itemDeleteTrigger()">Delete</TagsInput.ItemDeleteTrigger>
        </TagsInput.Item>
        <TagsInput.Input :class="styles.input()" placeholder="Add Framework" />
        <TagsInput.ClearTrigger :class="styles.clearTrigger()">Clear all</TagsInput.ClearTrigger>
      </TagsInput.Control>
    </TagsInput.Context>
    <TagsInput.HiddenInput />
  </TagsInput.Root>
</template>
