// packages/vue/.storybook/stories/components/tabs/disabled-tab.vue
<script setup lang="ts">
  import { type TabsStyles, tabsStyles } from "@bouquet-ui/design";
  import { Tabs } from "../../../../src";

  const props = defineProps<{
    variant?: "enclosed" | "line" | "outline" | undefined;
    size?: "sm" | "md" | "lg" | undefined;
  }>();
  const styles = tabsStyles(props);

  const options = [
    { id: "react", label: "React" },
    { id: "solid", label: "Solid" },
    { id: "svelte", label: "Svelte" },
    { id: "vue", label: "Vue" }
  ];
</script>

<template>
  <Tabs.Root :class="styles.root()" defaultValue="react">
    <Tabs.List :class="styles.list()">
      <Tabs.Trigger :class="styles.trigger()" v-for="option in options" :key="option.id" :value="option.id" :disabled="option.id === 'svelte'">
        {{option.label}}
      </Tabs.Trigger>
    <Tabs.Indicator :class="styles.indicator()" />
    </Tabs.List>
    <Tabs.Content :class="styles.content()" v-for="option in options" :key="option.id" :value="option.id">
      {{ option.label }} Content
    </Tabs.Content>
  </Tabs.Root>
</template>

// packages/svelte/.storybook/stories/components/tabs/disabled-tab.svelte
<script lang="ts">
  import { type TabsStyles, tabsStyles } from "@bouquet-ui/design";
  import { Tabs } from "../../../../src/lib";

  let props: TabsStyles.Variants = $props();
  const styles = tabsStyles(props);

  const options = [
    { id: "react", label: "React" },
    { id: "solid", label: "Solid" },
    { id: "svelte", label: "Svelte" },
    { id: "vue", label: "Vue" }
  ];
</script>

<Tabs.Root class={styles.root()}>
  <Tabs.List class={styles.list()}>
    {#each options as option (option.id)}
      <Tabs.Trigger class={styles.trigger()} value={option.id} disabled={option.id === "svelte"}>
        {option.label}
      </Tabs.Trigger>
    {/each}
    <Tabs.Indicator class={styles.indicator()} />
  </Tabs.List>
  {#each options as option (option.id)}
    <Tabs.Content class={styles.content()} value={option.id}>
      {option.label} Content
    </Tabs.Content>
  {/each}
</Tabs.Root>
