// packages/svelte/.storybook/stories/components/toggle/indicator.svelte
<script lang="ts">
  import { toggleStyles } from "@bouquet-ui/design";
  import { Volume, VolumeOff } from "lucide-svelte";
  import { Toggle } from "../../../../src/lib";

  let props: Toggle.RootProps = $props();
  const styles = toggleStyles();
</script>

<Toggle.Root {...props} class={styles.root()}>
  <Toggle.Indicator class={styles.indicator()}>
    {#snippet fallback()}
      <Volume />
    {/snippet}
    <VolumeOff />
  </Toggle.Indicator>
</Toggle.Root>

// packages/vue/.storybook/stories/components/toggle/indicator.vue
<script setup lang="ts">
  import { toggleStyles } from "@bouquet-ui/design";
  import { Volume, VolumeOff } from "lucide-vue-next";
  import { Toggle } from "../../../../src";

  const { disabled = false } = defineProps<{
    disabled?: boolean;
  }>();
  const styles = toggleStyles();
</script>

<template>
  <Toggle.Root :class="styles.root()" :disabled="disabled">
    <Toggle.Indicator :class="styles.indicator()">
      <template #fallback>
        <Volume />
      </template>
      <VolumeOff />
    </Toggle.Indicator>
  </Toggle.Root>
</template>
